version: '3'

services:
  server:
    shm_size: "300M"
    build: .
    container_name: BattleShipServer
    restart: always
    ports:
      - "12345:12345"
    privileged: true
    stdin_open: true
    tty: true
