name: CmakeBuild

on: [push]

jobs:
  build:
    strategy:
      matrix:
        build_what: [server, client]
        
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Installing libraries
        run: |
          sudo apt update
          sudo apt install -y libpqxx-dev libsfml-dev cmake ninja-build

      - name: Build ${{ matrix.build_what }}
        run: |
          cd ${{ matrix.build_what }}
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
          cd build
          cmake --build ./ --target battleship${{ matrix.build_what }} --config Release
