name: CmakeBuild

on: [push]

jobs:
  cmake-build:
    strategy:
      matrix:
        build_what: [server, client]
        
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Installing libraries
        run: |
          sudo apt update
          sudo apt install -y libpqxx-dev libsfml-dev cmake ninja-build

      - name: Build ${{ matrix.build_what }}
        run: |
          cd ${{ matrix.build_what }}
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
          cd build
          cmake --build ./ --config Release

      - name: Send status
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Run ${{ github.workflow }}(${{ matrix.build_what }}) ${{job.status}}
        env:
          status: ${{ job.status }}
