# Run clang-tidy
name: Clang-tidy

on: [push]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: 'tests'
        extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        cmakeoptions: ''
