name: Deploy server

on:
  push:
    branches: ["master"]
  workflow_run:
    workflows: ["CmakeBuild", "Docker", "Publish Docker image", "GoogleTests", "CppLint"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout
        uses: actions/checkout@v2

      - name: Updating server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ./server
            docker stop battleship-server
            docker rm battleship-server
            docker pull ${{ secrets.DOCKER_USERNAME }}/battleship-server:master
            docker-compose up -d --build
            
      - name: Send status
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Deploying last version of battleship-server on ${{ SSH_HOST }} ${{job.status}}
        env:
          status: ${{job.status}}
