name: Docker

on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setting up project
        run: touch ./server/config
      
      - name: Docker build
        run: docker-compose build

      - name: Send status
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Run ${{ github.workflow }} ${{job.status}}
        env:
          status: ${{job.status}}
