name: Publish Docker image

on:
  push:
    branches: ["master"]

jobs:
  push-to-dockerhub:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: raezhov/

      - name: Build the Docker image
        run: |
          docker build . --file ./Dockerfile --tag ${{ DOCKER_USERNAME }}/battleship-server:${{ steps.date.outputs.date }}    - name: Docker Push

      - name: Docker push
        run: docker push ${{ DOCKER_USERNAME }}/battleship-server:${{ steps.date.outputs.date }}

      - name: Send status
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Image uploaded to ${{ DOCKER_USERNAME }}/battleship-server:${{ steps.date.outputs.date }}
        env:
          status: ${{job.status}}
