name: GoogleTests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Installing libraries
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build libsfml-dev libpqxx-dev

      - name: Building Tests
        run: |
          cd tests
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
          cd build
          cmake --build ./ --target BattleShipTests --config Release
      - name: Running Tests
        run: ./tests/build/BattleShipTests

      - name: Send if falure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Run faied: ${{ github.workflow }} - ${{ steps.branch-name.outputs.current_branch }}.
        env:
          status: ${{job.status}}
